-- KUA Carbon Dashboard — initial methodology-driven schema
-- Conventions:
--   * every source table records data_quality (measured | estimated | modeled),
--     a free-text source pointer, and notes — never lose provenance.
--   * emission factors live in a versioned table; source rows hold quantities only.
--   * RLS is permissive for the anon role for now because the Admin Portal
--     authenticates client-side via password; tighten when real Supabase Auth
--     is wired up (Phase 2 of capstone plan).

create extension if not exists "pgcrypto";

-- ============================================================
-- 1. Versioned emission factors registry
-- ============================================================
-- A pre-existing empty placeholder table is replaced; verified 0 rows before drop.
drop table if exists emission_factors cascade;
create table emission_factors (
  id              bigint generated by default as identity primary key,
  factor_key      text   not null,
  value           numeric not null,
  unit            text   not null,
  source_citation text   not null,
  valid_from      date   not null,
  valid_to        date,
  notes           text,
  created_at      timestamptz default now(),
  unique (factor_key, valid_from)
);

-- ============================================================
-- 2. Audit log
-- ============================================================
create table if not exists audit_log (
  id          bigint generated by default as identity primary key,
  table_name  text not null,
  record_id   text,
  operation   text not null check (operation in ('insert','update','delete')),
  changed_by  text,
  changed_at  timestamptz default now(),
  before_json jsonb,
  after_json  jsonb
);

-- ============================================================
-- 3. Scope 1 — direct emissions
-- ============================================================
create table if not exists scope1_heating_oil (
  id               bigint generated by default as identity primary key,
  delivery_date    date    not null,
  vendor           text,
  invoice_number   text,
  building_or_tank text,
  gallons          numeric not null check (gallons >= 0),
  cost_usd         numeric,
  data_quality     text default 'measured' check (data_quality in ('measured','estimated','modeled')),
  source           text,
  notes            text,
  created_at       timestamptz default now()
);

create table if not exists scope1_propane (
  id               bigint generated by default as identity primary key,
  delivery_date    date    not null,
  vendor           text,
  invoice_number   text,
  building_or_tank text,
  gallons          numeric not null check (gallons >= 0),
  cost_usd         numeric,
  data_quality     text default 'measured' check (data_quality in ('measured','estimated','modeled')),
  source           text,
  notes            text,
  created_at       timestamptz default now()
);

-- Refrigerant emissions follow the GHG Protocol mass-balance approach:
--   emissions = (recharge_lb - reclaim_lb) * GWP100
-- GWP100 values come from emission_factors keyed e.g. 'gwp_r410a_ar6'.
create table if not exists scope1_refrigerants (
  id                    bigint generated by default as identity primary key,
  service_date          date not null,
  equipment_id          text,
  refrigerant_type      text not null,
  recharge_lb           numeric default 0 check (recharge_lb >= 0),
  reclaim_lb            numeric default 0 check (reclaim_lb >= 0),
  service_company       text,
  service_report_number text,
  data_quality          text default 'measured' check (data_quality in ('measured','estimated','modeled')),
  source                text,
  notes                 text,
  created_at            timestamptz default now()
);

create table if not exists scope1_fleet (
  id            bigint generated by default as identity primary key,
  period_start  date not null,
  period_end    date not null,
  vehicle_id    text,
  fuel_type     text not null check (fuel_type in ('gasoline','diesel','other')),
  gallons       numeric check (gallons is null or gallons >= 0),
  miles         numeric check (miles is null or miles >= 0),
  cost_usd      numeric,
  data_quality  text default 'measured' check (data_quality in ('measured','estimated','modeled')),
  source        text,
  notes         text,
  created_at    timestamptz default now(),
  check (gallons is not null or miles is not null)
);

-- ============================================================
-- 4. Scope 2 — purchased electricity
-- ============================================================
-- Campus real-time meter is the source of truth for quantity.
create table if not exists scope2_meter_readings (
  id            bigint generated by default as identity primary key,
  period_start  date not null,
  period_end    date not null,
  meter_id      text,
  building      text,
  kwh           numeric not null check (kwh >= 0),
  data_quality  text default 'measured' check (data_quality in ('measured','estimated','modeled')),
  source        text default 'campus_meter',
  notes         text,
  created_at    timestamptz default now()
);

-- Liberty Utilities monthly bills — for reconciliation only, NOT primary source.
create table if not exists scope2_utility_bills (
  id                   bigint generated by default as identity primary key,
  billing_period_start date not null,
  billing_period_end   date not null,
  utility              text default 'Liberty Utilities',
  kwh_billed           numeric not null check (kwh_billed >= 0),
  kwh_metered_compare  numeric,                         -- meter total over same period for delta check
  cost_usd             numeric,
  data_quality         text default 'measured' check (data_quality in ('measured','estimated','modeled')),
  source               text,                            -- e.g. 'liberty_pdf:202403.pdf'
  notes                text,
  created_at           timestamptz default now()
);

-- ============================================================
-- 5. Renewables
-- ============================================================
-- Self-consumed kWh reduce Scope 2 directly; exported kWh tracked separately
-- to avoid double-counting under net metering.
create table if not exists renewables_solar (
  id                  bigint generated by default as identity primary key,
  period_start        date not null,
  period_end          date not null,
  inverter_id         text,
  gross_kwh           numeric not null check (gross_kwh >= 0),
  self_consumed_kwh   numeric check (self_consumed_kwh is null or self_consumed_kwh >= 0),
  exported_kwh        numeric check (exported_kwh is null or exported_kwh >= 0),
  data_quality        text default 'measured' check (data_quality in ('measured','estimated','modeled')),
  source              text,
  notes               text,
  created_at          timestamptz default now()
);

-- Counterfactual: thermal_btu = kwh_input * cop * 3412.14
-- avoided_emissions = thermal_btu / fuel_btu_per_gal * fuel_factor_kg_per_gal
create table if not exists renewables_geothermal (
  id                bigint generated by default as identity primary key,
  period_start      date not null,
  period_end        date not null,
  system_id         text,
  kwh_input         numeric not null check (kwh_input >= 0),
  cop               numeric check (cop is null or cop > 0),
  avoided_fuel_type text check (avoided_fuel_type in ('heating_oil','propane','none')),
  data_quality      text default 'estimated' check (data_quality in ('measured','estimated','modeled')),
  source            text,
  notes             text,
  created_at        timestamptz default now()
);

-- Wind turbine: documented as offline asset per GHG Protocol honesty rule.
create table if not exists renewables_wind (
  id                    bigint generated by default as identity primary key,
  status                text not null check (status in ('online','offline','decommissioned')),
  as_of_date            date not null,
  last_operational_date date,
  rated_kw              numeric,
  hub_height_m          numeric,
  historical_kwh        numeric,
  data_quality          text default 'estimated' check (data_quality in ('measured','estimated','modeled')),
  source                text,
  notes                 text,
  created_at            timestamptz default now()
);

-- ============================================================
-- 6. Sinks — trees and soils
-- ============================================================
-- Per-tree DBH inventory feeds USDA Urban Tree Database allometrics.
-- Fallback: Nowak et al. (2013) canopy-area densities (7.69 kg C/m2 storage,
-- 0.28 kg C/m2/yr sequestration).
create table if not exists sinks_trees (
  id                  bigint generated by default as identity primary key,
  survey_date         date not null,
  tree_id             text,
  latitude            numeric,
  longitude           numeric,
  species_common      text,
  species_scientific  text,
  dbh_cm              numeric not null check (dbh_cm > 0),
  height_m            numeric check (height_m is null or height_m > 0),
  health_condition    text check (health_condition in ('good','fair','poor','dead')),
  land_class          text check (land_class in ('forest','lawn','athletic','garden','hardscape','other')),
  data_quality        text default 'measured' check (data_quality in ('measured','estimated','modeled')),
  source              text,
  notes               text,
  created_at          timestamptz default now()
);

-- Soil organic carbon stock per sample:
--   stock_t_per_ha = depth_cm * bulk_density_g_cm3 * (oc_percent/100) * 100
create table if not exists sinks_soil_samples (
  id                  bigint generated by default as identity primary key,
  sample_date         date not null,
  sample_id           text,
  latitude            numeric,
  longitude           numeric,
  land_use_class      text not null check (land_use_class in ('forest','lawn','athletic','garden','hardscape','other')),
  depth_cm_top        numeric default 0 check (depth_cm_top >= 0),
  depth_cm_bottom     numeric not null check (depth_cm_bottom > 0),
  bulk_density_g_cm3  numeric not null check (bulk_density_g_cm3 > 0),
  oc_percent          numeric not null check (oc_percent >= 0 and oc_percent <= 100),
  lab_method          text check (lab_method in ('dry_combustion','loss_on_ignition','other')),
  data_quality        text default 'measured' check (data_quality in ('measured','estimated','modeled')),
  source              text,
  notes               text,
  created_at          timestamptz default now(),
  check (depth_cm_bottom > depth_cm_top)
);

-- ============================================================
-- 7. Framework drafts (generic sandbox)
-- ============================================================
create table if not exists framework_drafts (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz default now(),
  scope        text not null,
  category     text,
  label        text not null,
  value        numeric,
  unit         text,
  date         date,
  source       text,
  data_quality text check (data_quality in ('measured','estimated','modeled')),
  notes        text
);

-- ============================================================
-- 8. RLS — enable on every table, then permissive policies for anon.
--    Tighten these when real Supabase Auth replaces the client-side gate.
-- ============================================================
do $$
declare t text;
begin
  for t in
    select unnest(array[
      'emission_factors','audit_log',
      'scope1_heating_oil','scope1_propane','scope1_refrigerants','scope1_fleet',
      'scope2_meter_readings','scope2_utility_bills',
      'renewables_solar','renewables_geothermal','renewables_wind',
      'sinks_trees','sinks_soil_samples',
      'framework_drafts'
    ])
  loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists "anon read"   on %I', t);
    execute format('drop policy if exists "anon write"  on %I', t);
    execute format('drop policy if exists "anon update" on %I', t);
    execute format('drop policy if exists "anon delete" on %I', t);
    execute format('create policy "anon read"   on %I for select using (true)', t);
    execute format('create policy "anon write"  on %I for insert with check (true)', t);
    execute format('create policy "anon update" on %I for update using (true) with check (true)', t);
    execute format('create policy "anon delete" on %I for delete using (true)', t);
  end loop;
end $$;

-- ============================================================
-- 9. Seed emission factors
-- ============================================================
insert into emission_factors (factor_key, value, unit, source_citation, valid_from, notes) values
  ('epa_heating_oil_co2_kg_per_gal', 10.16,  'kg CO2 / gal',  'EPA GHG Emission Factors Hub (2024), Table 2 — Distillate Fuel Oil No. 2', '2024-01-01', 'Stationary combustion, CO2 only'),
  ('epa_propane_co2_kg_per_gal',      5.72,  'kg CO2 / gal',  'EPA GHG Emission Factors Hub (2024), Table 2 — Propane',                  '2024-01-01', 'Stationary combustion, CO2 only'),
  ('epa_gasoline_co2_kg_per_gal',     8.78,  'kg CO2 / gal',  'EPA GHG Emission Factors Hub (2024) — Mobile Combustion, gasoline',       '2024-01-01', null),
  ('epa_diesel_co2_kg_per_gal',      10.21,  'kg CO2 / gal',  'EPA GHG Emission Factors Hub (2024) — Mobile Combustion, diesel',         '2024-01-01', null),
  ('iso_ne_grid_co2_lb_per_mwh',    643.0,   'lb CO2 / MWh',  'ISO New England Electric Generator Air Emissions Report 2024',           '2024-01-01', 'Location-based, regional generation'),
  ('iso_ne_imported_co2_lb_per_mwh',177.0,   'lb CO2 / MWh',  'ISO New England Electric Generator Air Emissions Report 2024',           '2024-01-01', 'Imported power; lower due to Canadian hydro share'),
  ('nowak_tree_storage_kg_c_per_m2',  7.69,  'kg C / m2',     'Nowak et al. (2013), Urban Forestry & Urban Greening',                    '2013-01-01', 'Whole-tree carbon storage density, urban average'),
  ('nowak_tree_seq_kg_c_per_m2_yr',   0.28,  'kg C / m2 / yr','Nowak et al. (2013), Urban Forestry & Urban Greening',                    '2013-01-01', 'Annual sequestration density, urban average'),
  ('gwp_r410a_ar6',                2256.0,   'gwp100',        'IPCC AR6, Working Group I, Chapter 7 Table 7.SM.7',                       '2021-01-01', 'GWP100 for R-410A blend'),
  ('gwp_r22_ar6',                  1960.0,   'gwp100',        'IPCC AR6, Working Group I, Chapter 7',                                    '2021-01-01', 'GWP100 for HCFC-22'),
  ('gwp_r134a_ar6',                1530.0,   'gwp100',        'IPCC AR6, Working Group I, Chapter 7',                                    '2021-01-01', 'GWP100 for HFC-134a'),
  ('gwp_r32_ar6',                   771.0,   'gwp100',        'IPCC AR6, Working Group I, Chapter 7',                                    '2021-01-01', 'GWP100 for HFC-32'),
  ('warm_landfill_kg_co2e_per_ton',  520.0,  'kg CO2e / ton', 'EPA WARM v15',                                                            '2024-01-01', 'Mixed MSW landfilled, default'),
  ('warm_recycling_kg_co2e_per_ton',-100.0,  'kg CO2e / ton', 'EPA WARM v15',                                                            '2024-01-01', 'Mixed recyclables, net of avoided virgin production'),
  ('warm_compost_kg_co2e_per_ton',    40.0,  'kg CO2e / ton', 'EPA WARM v15',                                                            '2024-01-01', 'Food waste, composted'),
  ('defra_air_long_haul_kg_co2e_per_pkm', 0.195, 'kg CO2e / pkm', 'DEFRA 2024 conversion factors (long-haul, economy)',                  '2024-01-01', 'Includes radiative forcing multiplier')
on conflict (factor_key, valid_from) do nothing;

-- Ask PostgREST to reload its schema cache so new tables are immediately queryable via the REST API.
notify pgrst, 'reload schema';
