-- Adds the two Scope 3 categories that previously shipped as stubs only:
--   Cat 1: Purchased Goods & Services (EPA Supply Chain EEIO, spend-based)
--   Cat 7: Employee Commuting (EPA per-passenger-mile by mode)

create table if not exists purchased_goods (
  id                   bigint generated by default as identity primary key,
  fiscal_year          text not null,
  purchasing_category  text not null,
  spend_usd            numeric not null check (spend_usd >= 0),
  eeio_factor_override numeric,        -- nullable; falls back to emission_factors lookup at report time
  data_quality         text default 'estimated' check (data_quality in ('measured','estimated','modeled')),
  source               text,
  notes                text,
  created_at           timestamptz default now()
);

create table if not exists commuting (
  id              bigint generated by default as identity primary key,
  school_year     text not null,
  employee_role   text check (employee_role in ('faculty','staff','student','other')),
  home_zip        text,
  one_way_miles   numeric not null check (one_way_miles >= 0),
  mode            text not null check (mode in ('car_solo','carpool','transit','bike','walk','ev')),
  days_per_week   numeric default 5 check (days_per_week >= 0 and days_per_week <= 7),
  weeks_per_year  numeric default 36 check (weeks_per_year >= 0),
  survey_date     date,
  data_quality    text default 'estimated' check (data_quality in ('measured','estimated','modeled')),
  source          text,
  notes           text,
  created_at      timestamptz default now()
);

do $$
declare t text;
begin
  for t in select unnest(array['purchased_goods','commuting'])
  loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists "anon read"   on %I', t);
    execute format('drop policy if exists "anon write"  on %I', t);
    execute format('drop policy if exists "anon update" on %I', t);
    execute format('drop policy if exists "anon delete" on %I', t);
    execute format('create policy "anon read"   on %I for select using (true)', t);
    execute format('create policy "anon write"  on %I for insert with check (true)', t);
    execute format('create policy "anon update" on %I for update using (true) with check (true)', t);
    execute format('create policy "anon delete" on %I for delete using (true)', t);
  end loop;
end $$;

-- Spend-based EEIO factors (rough school-relevant approximations from
-- EPA Supply Chain v1.2). Replace with NAICS-specific values when the
-- accounting system tags purchases by industry code.
insert into emission_factors (factor_key, value, unit, source_citation, valid_from, notes) values
  ('eeio_food_kg_co2e_per_usd',         0.55, 'kg CO2e / USD',           'EPA Supply Chain GHG Emission Factors v1.2', '2024-01-01', 'Food services / dining'),
  ('eeio_paper_kg_co2e_per_usd',        0.65, 'kg CO2e / USD',           'EPA Supply Chain GHG Emission Factors v1.2', '2024-01-01', 'Paper, office supplies'),
  ('eeio_it_kg_co2e_per_usd',           0.30, 'kg CO2e / USD',           'EPA Supply Chain GHG Emission Factors v1.2', '2024-01-01', 'IT equipment, electronics'),
  ('eeio_athletic_kg_co2e_per_usd',     0.20, 'kg CO2e / USD',           'EPA Supply Chain GHG Emission Factors v1.2', '2024-01-01', 'Athletic equipment'),
  ('eeio_lab_kg_co2e_per_usd',          0.85, 'kg CO2e / USD',           'EPA Supply Chain GHG Emission Factors v1.2', '2024-01-01', 'Lab supplies, chemicals'),
  ('eeio_construction_kg_co2e_per_usd', 0.50, 'kg CO2e / USD',           'EPA Supply Chain GHG Emission Factors v1.2', '2024-01-01', 'Construction materials'),
  ('eeio_cleaning_kg_co2e_per_usd',     0.50, 'kg CO2e / USD',           'EPA Supply Chain GHG Emission Factors v1.2', '2024-01-01', 'Cleaning supplies'),
  ('eeio_generic_kg_co2e_per_usd',      0.45, 'kg CO2e / USD',           'EPA Supply Chain GHG Emission Factors v1.2', '2024-01-01', 'Generic / uncategorized'),
  ('epa_commute_car_solo_kg_co2e_per_pmi', 0.404, 'kg CO2e / passenger-mile', 'EPA GHG Emission Factors Hub — Mobile Combustion',     '2024-01-01', 'Single-occupant gasoline passenger car'),
  ('epa_commute_carpool_kg_co2e_per_pmi',  0.202, 'kg CO2e / passenger-mile', 'EPA GHG Emission Factors Hub — Mobile Combustion',     '2024-01-01', 'Two-occupant carpool (per passenger)'),
  ('epa_commute_transit_kg_co2e_per_pmi',  0.108, 'kg CO2e / passenger-mile', 'EPA GHG Emission Factors Hub — Public Transportation','2024-01-01', 'Bus / commuter rail average'),
  ('epa_commute_bike_kg_co2e_per_pmi',     0.000, 'kg CO2e / passenger-mile', 'Definitional',                                         '2024-01-01', 'Zero direct emissions'),
  ('epa_commute_walk_kg_co2e_per_pmi',     0.000, 'kg CO2e / passenger-mile', 'Definitional',                                         '2024-01-01', 'Zero direct emissions'),
  ('epa_commute_ev_kg_co2e_per_pmi',       0.150, 'kg CO2e / passenger-mile', 'EPA GHG Hub + ISO-NE 2024 grid factor',                '2024-01-01', 'EV on regional grid average')
on conflict (factor_key, valid_from) do nothing;

notify pgrst, 'reload schema';
