import React, { useState } from 'react';
import { useTable } from './scope3/useTable';
import { formStyles as s } from './scope3/formStyles';

const scopes = ['Scope 1', 'Scope 2', 'Scope 3', 'Renewables', 'Sinks', 'Other'];
const dataQualities = ['measured', 'estimated', 'modeled'];

const empty = {
  scope: 'Scope 1',
  category: '',
  label: '',
  value: '',
  unit: '',
  date: '',
  source: '',
  data_quality: 'measured',
  notes: '',
};

const sql = `create table if not exists framework_drafts (
  id           bigint generated by default as identity primary key,
  created_at   timestamp with time zone default now(),
  scope        text not null,
  category     text,
  label        text not null,
  value        numeric,
  unit         text,
  date         date,
  source       text,
  data_quality text check (data_quality in ('measured','estimated','modeled')),
  notes        text
);

alter table framework_drafts enable row level security;
create policy "anon read"   on framework_drafts for select using (true);
create policy "anon write"  on framework_drafts for insert with check (true);
create policy "anon delete" on framework_drafts for delete using (true);`;

const styles = {
  banner: { marginTop: 16, padding: 12, background: '#0f172a', border: '1px dashed #334155', borderRadius: 8, color: '#94a3b8', fontSize: 13 },
  sqlBlock: { marginTop: 12, padding: 12, background: '#0b1220', border: '1px solid #1f2937', borderRadius: 6, fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace', fontSize: 12, color: '#cbd5e1', whiteSpace: 'pre', overflowX: 'auto', lineHeight: 1.5 },
  toggle: { marginTop: 8, background: 'transparent', border: '1px solid #334155', color: '#cbd5e1', padding: '4px 10px', borderRadius: 6, fontSize: 12, cursor: 'pointer' },
  pill: (q) => ({ fontSize: 11, padding: '2px 8px', borderRadius: 999, background: q === 'measured' ? '#052e1a' : q === 'estimated' ? '#3a2a0d' : '#1e293b', color: q === 'measured' ? '#86efac' : q === 'estimated' ? '#fbbf24' : '#94a3b8' }),
};

function AdminFramework() {
  const { rows, error, insert, remove } = useTable('framework_drafts', 'created_at');
  const [form, setForm] = useState(empty);
  const [msg, setMsg] = useState(null);
  const [showSql, setShowSql] = useState(false);

  const submit = async (e) => {
    e.preventDefault();
    let valueNum = null;
    if (form.value !== '') {
      valueNum = parseFloat(form.value);
      if (!Number.isFinite(valueNum)) {
        setMsg({ ok: false, text: `Value must be a finite number (got "${form.value}")` });
        return;
      }
    }
    try {
      await insert({
        scope: form.scope,
        category: form.category || null,
        label: form.label,
        value: valueNum,
        unit: form.unit || null,
        date: form.date || null,
        source: form.source || null,
        data_quality: form.data_quality,
        notes: form.notes || null,
      });
      setForm({ ...empty, scope: form.scope });
      setMsg({ ok: true, text: 'Draft entry saved.' });
    } catch (err) {
      setMsg({ ok: false, text: err.message });
    }
  };

  const onDelete = async (id) => {
    if (!window.confirm('Delete this draft?')) return;
    try { await remove(id); } catch (err) { setMsg({ ok: false, text: err.message }); }
  };

  const tableMissing = error && /relation .* does not exist|Could not find the table|404/i.test(error);

  return (
    <div>
      <div style={s.cat}>Admin · Sandbox</div>
      <h1 style={s.title}>Framework Data Entry</h1>
      <p style={s.subtitle}>
        Generic input for any scope or category. Use this while per-category forms and tables are
        still being designed — every row records its own scope, label, value, source, and data
        quality, so nothing is lost when entries are later migrated to a typed table.
      </p>

      {tableMissing && (
        <div style={styles.banner}>
          <strong style={{ color: '#fbbf24' }}>Table <code>framework_drafts</code> does not exist yet.</strong>
          {' '}Create it in Supabase (SQL editor) using the block below, then refresh.
          <button type="button" style={styles.toggle} onClick={() => setShowSql((v) => !v)}>
            {showSql ? 'Hide SQL' : 'Show SQL'}
          </button>
          {showSql && <pre style={styles.sqlBlock}>{sql}</pre>}
        </div>
      )}

      {msg && <div style={{ ...s.msg, ...(msg.ok ? s.msgOk : s.msgErr) }}>{msg.text}</div>}

      <form style={s.card} onSubmit={submit}>
        <h2 style={s.h2}>New entry</h2>
        <div style={s.formGrid}>
          <label style={s.field}>
            <span style={s.label}>Scope</span>
            <select value={form.scope} onChange={(e) => setForm({ ...form, scope: e.target.value })} style={s.input}>
              {scopes.map((sc) => <option key={sc}>{sc}</option>)}
            </select>
          </label>
          <label style={s.field}>
            <span style={s.label}>Category</span>
            <input type="text" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} style={s.input} placeholder="e.g. Heating Fuel · Cat 6 · Trees" />
          </label>
          <label style={s.field}>
            <span style={s.label}>Label</span>
            <input type="text" value={form.label} onChange={(e) => setForm({ ...form, label: e.target.value })} style={s.input} placeholder="What this row records" required />
          </label>
          <label style={s.field}>
            <span style={s.label}>Value</span>
            <input type="number" step="any" value={form.value} onChange={(e) => setForm({ ...form, value: e.target.value })} style={s.input} placeholder="numeric, optional" />
          </label>
          <label style={s.field}>
            <span style={s.label}>Unit</span>
            <input type="text" value={form.unit} onChange={(e) => setForm({ ...form, unit: e.target.value })} style={s.input} placeholder="kWh · gal · lb · m² · ..." />
          </label>
          <label style={s.field}>
            <span style={s.label}>Date</span>
            <input type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} style={s.input} />
          </label>
          <label style={s.field}>
            <span style={s.label}>Data quality</span>
            <select value={form.data_quality} onChange={(e) => setForm({ ...form, data_quality: e.target.value })} style={s.input}>
              {dataQualities.map((q) => <option key={q}>{q}</option>)}
            </select>
          </label>
          <label style={{ ...s.field, ...s.full }}>
            <span style={s.label}>Source</span>
            <input type="text" value={form.source} onChange={(e) => setForm({ ...form, source: e.target.value })} style={s.input} placeholder="Invoice #, meter export, survey, etc." />
          </label>
          <label style={{ ...s.field, ...s.full }}>
            <span style={s.label}>Notes</span>
            <input type="text" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} style={s.input} placeholder="optional" />
          </label>
        </div>
        <button type="submit" style={s.submit}>Save draft</button>
      </form>

      <h2 style={s.recordsTitle}>Recent drafts</h2>
      {error && !tableMissing && <div style={{ ...s.msg, ...s.msgErr }}>{error}</div>}
      {rows.length === 0 ? (
        <div style={s.empty}>{tableMissing ? 'Create the table to start saving entries.' : 'No drafts yet.'}</div>
      ) : (
        <table style={s.table}>
          <thead>
            <tr>
              <th style={s.th}>Scope</th>
              <th style={s.th}>Category</th>
              <th style={s.th}>Label</th>
              <th style={s.th}>Value</th>
              <th style={s.th}>Date</th>
              <th style={s.th}>Quality</th>
              <th style={s.th}></th>
            </tr>
          </thead>
          <tbody>
            {rows.map((r) => (
              <tr key={r.id}>
                <td style={s.td}>{r.scope}</td>
                <td style={s.td}>{r.category || '—'}</td>
                <td style={s.td}>{r.label}</td>
                <td style={s.td}>{r.value != null ? `${r.value}${r.unit ? ' ' + r.unit : ''}` : '—'}</td>
                <td style={s.td}>{r.date || '—'}</td>
                <td style={s.td}><span style={styles.pill(r.data_quality)}>{r.data_quality || '—'}</span></td>
                <td style={s.td}><button type="button" style={s.delBtn} onClick={() => onDelete(r.id)}>Delete</button></td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
}

export default AdminFramework;
