import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ModulePage, ModuleSection, MetricGrid, Pill } from '../../components/ModuleShell.js';
import { ProvenancePill } from '../../components/ProvenancePill.js';
import { useBmsExport, BMS_EXPORT_TABLE } from '../../hooks/useBmsExport.js';
import { parseMeterTrendsHourly } from '../../data/parseBmsExport.js';
import { annualizeFactorForWindow } from '../../data/composedYtd.js';

// Shorter windows get annualized by an enormous multiplier — a 3-day file
// would scale ×122 — so a stray partial export can't become a building's year.
const MIN_EXPORT_DAYS = 14;
import { supabase } from '../../supabaseClient.js';
import { logAdminWrite } from '../../utils/adminAudit.js';
import { getBmsMeterMap, setBmsMeterMapping, clearBmsMeterMappings, hydrateBmsMeterMap } from '../../data/bmsExportMapping.js';
import { getEffectiveBuildings } from '../../data/assetInventory.js';

// /admin/bms-export — read-only view of the parsed BMS Meter Trends
// CSV plus a meter→building mapping form. Once a meter is mapped, the
// /api/meters/readings endpoint and the public /buildings + /hotspots
// pages start showing measured data for that building.
//
// The export itself is regenerated by re-running
//   node scripts/parseBmsExport.mjs <new.csv> src/data/bmsExportApr2026.js
// and committing the result. This page does not ingest a CSV directly
// — that's a follow-up if the CSV-upload-in-browser flow is wanted.

export default function AdminBmsExport() {
  const [tick, setTick] = useState(0);
  const refresh = () => setTick((t) => t + 1);
  // Pull the shared mapping once so this page shows what every admin sees,
  // not just what this browser has in localStorage.
  const [shared, setShared] = useState(null);
  useEffect(() => {
    let cancelled = false;
    hydrateBmsMeterMap().then((res) => {
      if (cancelled) return;
      setShared(res);
      setTick((t) => t + 1);
    });
    return () => { cancelled = true; };
  }, []);
  const [filter, setFilter] = useState('');
  const [showOnlyUnmapped, setShowOnlyUnmapped] = useState(false);

  // The active hourly export: the newest uploaded window, or the module
  // committed in the app when nothing has been uploaded. Names kept from the
  // static import this page used to read, so the view below is unchanged.
  const activeExport = useBmsExport();
  const BMS_EXPORT_META = activeExport.meta;
  const bmsExportMeters = activeExport.meters;

  const [upload, setUpload] = useState(null);
  const [uploads, setUploads] = useState([]);
  const [uploadMsg, setUploadMsg] = useState(null);
  const [busy, setBusy] = useState(false);
  const savingRef = useRef(false);

  // List stored uploads WITHOUT their summaries — each is ~340 KB, and this
  // list only needs the window.
  const refreshUploads = useCallback(async () => {
    try {
      const { data, error } = await supabase
        .from(BMS_EXPORT_TABLE)
        .select('id, source_file, window_start, window_end, hours_covered, meter_count, created_at')
        .order('created_at', { ascending: false })
        .limit(20);
      setUploads(error ? [] : (data || []));
    } catch { setUploads([]); }
  }, []);
  useEffect(() => { refreshUploads(); }, [refreshUploads]);

  const onExportFile = async (e) => {
    const file = e.target.files?.[0];
    setUploadMsg(null);
    setUpload(null);
    if (!file) return;
    try {
      const parsed = parseMeterTrendsHourly(await file.text(), file.name);
      setUpload(parsed);
    } catch (err) {
      setUploadMsg({ ok: false, text: `Couldn't read that export: ${err.message}` });
    }
  };

  const saveUpload = async () => {
    if (!upload || savingRef.current) return;
    const days = Math.round((new Date(upload.meta.windowEndIso) - new Date(upload.meta.windowStartIso)) / 86400000);
    if (days < MIN_EXPORT_DAYS) {
      setUploadMsg({ ok: false, text: `That window covers ${days} day${days === 1 ? '' : 's'}. Anything under ${MIN_EXPORT_DAYS} days gets annualized by a huge multiplier, so it would distort every building's year — export at least two weeks.` });
      return;
    }
    if (!annualizeFactorForWindow(upload.meta.windowStartIso.slice(0, 10), upload.meta.windowEndIso.slice(0, 10))) {
      setUploadMsg({ ok: false, text: `That window (${upload.meta.windowStartIso.slice(0, 10)} → ${upload.meta.windowEndIso.slice(0, 10)}) falls outside the year the dashboard reports, so it can't be annualized. Upload an export from the current reporting year.` });
      return;
    }
    savingRef.current = true;
    setBusy(true);
    try {
      const row = {
        source_file: upload.meta.sourceFile,
        window_start: upload.meta.windowStartIso,
        window_end: upload.meta.windowEndIso,
        hours_covered: upload.meta.hoursCovered,
        meter_count: upload.meta.meterCount,
        summary: upload.meters,
      };
      const { error } = await supabase.from(BMS_EXPORT_TABLE).insert([row]);
      if (error) throw error;
      logAdminWrite({ action: 'insert', table: BMS_EXPORT_TABLE, payload: { source_file: row.source_file, window_end: row.window_end, meter_count: row.meter_count } });
      setUploadMsg({ ok: true, text: `Saved ${upload.meta.sourceFile}. Reload to draw the operational views from it.` });
      setUpload(null);
      await refreshUploads();
    } catch (err) {
      setUploadMsg({ ok: false, text: `${err.message}. If the table is missing, apply supabase/migrations/20260915140000_bms_export_summaries.sql.` });
    } finally {
      savingRef.current = false;
      setBusy(false);
    }
  };

  const deleteUpload = async (row) => {
    if (savingRef.current) return;
    if (!window.confirm(`Delete the ${row.source_file} window? The dashboard falls back to the next newest, or to the export committed in the app.`)) return;
    savingRef.current = true;
    setBusy(true);
    try {
      const { error } = await supabase.from(BMS_EXPORT_TABLE).delete().eq('id', row.id);
      if (error) throw error;
      logAdminWrite({ action: 'delete', table: BMS_EXPORT_TABLE, payload: { id: row.id, source_file: row.source_file } });
      await refreshUploads();
      setUploadMsg({ ok: true, text: `Deleted ${row.source_file}. Reload to see the change.` });
    } catch (err) {
      setUploadMsg({ ok: false, text: err.message });
    } finally {
      savingRef.current = false;
      setBusy(false);
    }
  };

  const buildings = useMemo(() => getEffectiveBuildings(), []);
  const map = useMemo(() => getBmsMeterMap(), [tick]);

  // Headline counts.
  const mappedCount = bmsExportMeters.filter((m) => map[m.id]).length;
  const stuckCount = bmsExportMeters.filter((m) => m.direction === 'stuck').length;
  const generationCount = bmsExportMeters.filter((m) => m.direction === 'generation').length;
  // Sum only consumption-direction meters for the headline total.
  // Generation-direction (solar / suspect-CT) meters would either be
  // double-counting or sign-flipped if added to the consumption sum.
  const totalConsumptionKwh = bmsExportMeters
    .filter((m) => m.direction === 'consumption')
    .reduce((s, m) => s + m.totalKwh, 0);

  const filteredRows = bmsExportMeters
    .filter((m) => !filter || m.id.toLowerCase().includes(filter.toLowerCase()))
    .filter((m) => !showOnlyUnmapped || !map[m.id]);

  return (
    <ModulePage
      title="BMS Meter Trends export"
      subtitle="Compact summary parsed from the KUA Distech Eclypse Meter Trends CSV. Map each PM device to a building below — once mapped, every chart on the dashboard that touches that building flips estimated → measured for the export window."
    >
      <ModuleSection title="Source window">
        <MetricGrid metrics={[
          { label: 'Window start',    value: BMS_EXPORT_META.windowStartIso.slice(0, 16).replace('T', ' '), accent: '#22d3ee' },
          { label: 'Window end',      value: BMS_EXPORT_META.windowEndIso.slice(0, 16).replace('T', ' '),   accent: '#22d3ee' },
          { label: 'Hours covered',   value: BMS_EXPORT_META.hoursCovered,                                  accent: '#fbbf24' },
          { label: 'Meters',          value: BMS_EXPORT_META.meterCount,                                    accent: '#86efac' },
          { label: 'Mapped → building', value: `${mappedCount} / ${BMS_EXPORT_META.meterCount}`,            accent: mappedCount === BMS_EXPORT_META.meterCount ? '#22c55e' : '#f59e0b' },
          { label: 'Total consumption kWh', value: Math.round(totalConsumptionKwh).toLocaleString(),       accent: '#a855f7', note: 'consumption-direction meters only' },
          { label: 'Stuck / not reporting',   value: stuckCount,                                            accent: stuckCount === 0 ? '#22c55e' : '#fbbf24' },
          { label: 'Generation / suspect-CT', value: generationCount,                                       accent: generationCount === 0 ? '#22c55e' : '#fbbf24', note: 'real solar + backwards CTs' },
        ]} />
        <div style={styles.metaRow}>
          <ProvenancePill provenance="measured" />
          <span style={styles.metaText}>Source: <code>{BMS_EXPORT_META.sourceFile}</code> · parsed {BMS_EXPORT_META.generatedAt.slice(0, 10)}</span>
          <span style={styles.metaText}>
            {activeExport.fromUpload
              ? 'Drawn from the newest export uploaded below.'
              : 'Drawn from the export committed in the app — upload a newer one below to replace it without a deploy.'}
          </span>
          <span style={styles.metaText}>
            {shared?.ok
              ? `Meter→building mapping is shared with every admin (${shared.rows} row${shared.rows === 1 ? '' : 's'} saved).`
              : 'Meter→building mapping is saved in this browser only. Apply supabase/migrations/20260915120000_bms_meter_map.sql to share it with the other admins.'}
          </span>
        </div>
      </ModuleSection>

      <ModuleSection
        title="Upload a newer hourly export"
        hint="The hourly Meter Trends CSV (one reading per hour). It's parsed in your browser with the same code the command-line script runs — nothing is saved until you confirm."
      >
        {uploadMsg && (
          <div style={{ ...styles.metaText, color: uploadMsg.ok ? '#86efac' : '#fca5a5', marginBottom: 10 }}>{uploadMsg.text}</div>
        )}
        <input type="file" accept=".csv,text/csv" onChange={onExportFile} style={styles.input} />

        {upload && (
          <div style={{ marginTop: 14 }}>
            <MetricGrid metrics={[
              { label: 'Window start', value: upload.meta.windowStartIso.slice(0, 16).replace('T', ' '), accent: '#22d3ee' },
              { label: 'Window end',   value: upload.meta.windowEndIso.slice(0, 16).replace('T', ' '),   accent: '#22d3ee' },
              { label: 'Hours',        value: upload.meta.hoursCovered,                                  accent: '#fbbf24' },
              { label: 'Meters',       value: upload.meta.meterCount,                                    accent: '#86efac' },
              {
                label: 'Annualize factor',
                value: (() => {
                  const f = annualizeFactorForWindow(upload.meta.windowStartIso.slice(0, 10), upload.meta.windowEndIso.slice(0, 10));
                  return f ? `×${f.toFixed(1)}` : 'n/a';
                })(),
                accent: '#a855f7',
                note: 'what a window total is multiplied by for the per-building year',
              },
            ]} />
            <div style={styles.metaRow}>
              <span style={styles.metaText}>
                Biggest loads: {upload.meters.slice(0, 3).map((m) => `${m.id} ${Math.round(m.totalKwh).toLocaleString()} kWh`).join(' · ')}
              </span>
            </div>
            <button type="button" onClick={saveUpload} disabled={busy} style={styles.primaryBtn}>
              Save this window
            </button>
          </div>
        )}

        {uploads.length > 0 && (
          <div style={{ marginTop: 16 }}>
            <div style={styles.metaText}>Stored windows (newest first) — the top one is what the dashboard draws:</div>
            <ul style={styles.flipList}>
              {uploads.map((u) => (
                <li key={u.id}>
                  <code>{u.source_file}</code> · {String(u.window_start).slice(0, 10)} → {String(u.window_end).slice(0, 10)} · {u.hours_covered} h · {u.meter_count} meters
                  {' '}<button type="button" onClick={() => deleteUpload(u)} style={{ background: 'transparent', border: 'none', color: '#f87171', cursor: 'pointer', fontSize: 12 }}>Delete</button>
                </li>
              ))}
            </ul>
          </div>
        )}
      </ModuleSection>

      <ModuleSection
        title={`Meters (${filteredRows.length} of ${bmsExportMeters.length})`}
        hint="Sorted by total kWh in the window. Use the dropdown on each row to map PM devices to KUA buildings — once mapped, the dashboard reads measured data for that building's load shape."
      >
        <div style={styles.controls}>
          <input
            type="text"
            value={filter}
            onChange={(e) => setFilter(e.target.value)}
            placeholder="Filter by meter id (e.g. PM_17, Solar, Dryer)"
            style={styles.input}
          />
          <label style={styles.checkboxLabel}>
            <input type="checkbox" checked={showOnlyUnmapped} onChange={(e) => setShowOnlyUnmapped(e.target.checked)} />
            Show only unmapped
          </label>
          <button
            type="button"
            style={styles.dangerBtn}
            onClick={() => {
              if (window.confirm('Clear ALL meter→building mappings? Every mapped building drops back to estimated on /buildings, /hotspots and the dorm leaderboard, for everyone. This cannot be undone.')) {
                clearBmsMeterMappings();
                refresh();
              }
            }}
          >
            Clear all mappings
          </button>
        </div>

        <div style={styles.list}>
          {filteredRows.map((m) => (
            <MeterRow
              key={m.id}
              meter={m}
              mappedTo={map[m.id]}
              buildings={buildings}
              onMap={(buildingId) => { setBmsMeterMapping(m.id, buildingId); refresh(); }}
            />
          ))}
        </div>
      </ModuleSection>

      <ModuleSection title="What flips estimated → measured once mapped">
        <ul style={styles.flipList}>
          <li><Pill kind="info">/buildings</Pill> the building's daily kWh column for the export window switches from seasonal-pattern proxy to BMS-measured.</li>
          <li><Pill kind="info">/buildings sparkline</Pill> the campus seasonal pattern adds the measured stretch from this window ({BMS_EXPORT_META.windowStartIso.slice(0, 10)} – {BMS_EXPORT_META.windowEndIso.slice(0, 10)}) on top of the master-meter months.</li>
          <li><Pill kind="info">/hotspots</Pill> daily totals inside that window come from the export rather than the projection layer.</li>
          <li><Pill kind="info">/trends</Pill> Trend Builder picks up the new meter ids in the building dropdown; selecting one returns hourly samples from the parsed export.</li>
          <li><Pill kind="info">Solar arrays</Pill> mapped solar feeds (PM_15_RoofTopSolarFeed, PM_15_FieldSolarFeed, PM_19_SolarFeed) become the cited source for SOLAR_ANNUAL_KWH on the Executive page.</li>
        </ul>
      </ModuleSection>
    </ModulePage>
  );
}

function MeterRow({ meter, mappedTo, buildings, onMap }) {
  const [expanded, setExpanded] = useState(false);
  const looksLikeSolar = /Solar/i.test(meter.id);
  const looksLikeHeatPump = /HP\d|HeatPump/i.test(meter.id);
  const looksLikeSubmeter = !meter.id.endsWith('MainFeed');

  return (
    <div style={{ ...styles.row, borderLeftColor: mappedTo ? '#22c55e' : '#475569' }}>
      <div style={styles.rowHead}>
        <div style={styles.rowMain}>
          <div style={styles.rowName}>
            <code>{meter.id}</code>
            {looksLikeSolar    && <span style={{ marginLeft: 8 }}><Pill kind="good">Solar</Pill></span>}
            {looksLikeHeatPump && <span style={{ marginLeft: 8 }}><Pill kind="info">Heat pump</Pill></span>}
            {looksLikeSubmeter && <span style={{ marginLeft: 8 }}><Pill kind="neutral">Submeter</Pill></span>}
          </div>
          <div style={styles.rowStats}>
            <span><strong>{meter.totalKwh.toLocaleString()}</strong> kWh</span>
            <span>peak <strong>{meter.peakKw}</strong> kW</span>
            <span>avg <strong>{meter.avgKw}</strong> kW</span>
            <span>{meter.sampleCount} samples</span>
            {meter.droppedOutliers > 0 && <span style={styles.dropped}>{meter.droppedOutliers} outlier{meter.droppedOutliers === 1 ? '' : 's'} filtered</span>}
          </div>
        </div>
        <div style={styles.rowMapping}>
          <select
            value={mappedTo || ''}
            onChange={(e) => onMap(e.target.value || null)}
            style={styles.select}
          >
            <option value="">— unmapped —</option>
            {buildings.map((b) => (
              <option key={b.id} value={b.id}>{b.name}</option>
            ))}
          </select>
          <button
            type="button"
            style={styles.expandBtn}
            aria-expanded={expanded}
            aria-controls={`bms-meter-detail-${meter.id}`}
            onClick={() => setExpanded((v) => !v)}
          >
            {expanded ? 'Hide' : 'Detail'}
          </button>
        </div>
      </div>
      {expanded && (
        <div id={`bms-meter-detail-${meter.id}`} style={styles.detailGrid}>
          <div>
            <div style={styles.detailTitle}>Hour-of-day load shape (mean kW)</div>
            <HourlyBars hourly={meter.hourly} />
          </div>
          <div>
            <div style={styles.detailTitle}>Daily totals (kWh)</div>
            <DailyBars daily={meter.daily} />
          </div>
        </div>
      )}
    </div>
  );
}

function HourlyBars({ hourly }) {
  const max = Math.max(...hourly, 1);
  return (
    <div style={styles.barsRow}>
      {hourly.map((kw, i) => (
        <div key={i} style={styles.barCol}>
          <div style={{ ...styles.bar, height: `${Math.round((kw / max) * 100)}%`, background: i >= 6 && i < 18 ? '#fbbf24' : '#475569' }} title={`${i}:00 — ${kw} kW`} />
          {(i % 6 === 0 || i === 23) && <div style={styles.barTick}>{i}</div>}
        </div>
      ))}
    </div>
  );
}

function DailyBars({ daily }) {
  if (!daily.length) return <div style={{ fontSize: 11, color: '#64748b' }}>No daily data.</div>;
  const max = Math.max(...daily.map((d) => d.kwh), 1);
  return (
    <div style={styles.barsRow}>
      {daily.map((d, i) => (
        <div key={d.date} style={styles.barCol}>
          <div style={{ ...styles.bar, height: `${Math.round((d.kwh / max) * 100)}%`, background: '#22c55e' }} title={`${d.date} — ${d.kwh.toLocaleString()} kWh, peak ${d.peakKw} kW`} />
          {(i === 0 || i === daily.length - 1 || i % 7 === 0) && <div style={styles.barTick}>{d.date.slice(5)}</div>}
        </div>
      ))}
    </div>
  );
}

const styles = {
  metaRow: { display: 'flex', gap: 18, alignItems: 'center', marginTop: 14, flexWrap: 'wrap', fontSize: 12, color: '#94a3b8' },
  metaText: { fontSize: 12, color: '#94a3b8' },
  controls: { display: 'flex', gap: 12, marginBottom: 14, alignItems: 'center', flexWrap: 'wrap' },
  input: { padding: '8px 12px', background: '#0b1220', border: '1px solid #334155', borderRadius: 6, color: '#e5e7eb', fontSize: 13, minWidth: 280 },
  checkboxLabel: { display: 'flex', alignItems: 'center', gap: 6, fontSize: 13, color: '#cbd5e1' },
  primaryBtn: { padding: '8px 14px', background: '#134e4a', color: '#99f6e4', border: '1px solid #115e59', borderRadius: 6, fontSize: 12, cursor: 'pointer', fontWeight: 600 },
  dangerBtn: { padding: '8px 14px', background: 'transparent', color: '#fca5a5', border: '1px solid #7f1d1d', borderRadius: 6, fontSize: 12, cursor: 'pointer' },
  list: { display: 'grid', gap: 6 },
  row: { padding: '10px 12px', background: '#0b1220', border: '1px solid #1f2937', borderLeft: '4px solid #475569', borderRadius: 6 },
  rowHead: { display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'center', flexWrap: 'wrap' },
  rowMain: { flex: 1 },
  rowName: { fontSize: 13, color: '#e5e7eb', fontWeight: 600 },
  rowStats: { display: 'flex', gap: 14, marginTop: 4, fontSize: 12, color: '#94a3b8', flexWrap: 'wrap', fontVariantNumeric: 'tabular-nums' },
  dropped: { color: '#fbbf24' },
  rowMapping: { display: 'flex', gap: 6, alignItems: 'center' },
  select: { padding: '6px 8px', background: '#0b1220', border: '1px solid #334155', borderRadius: 4, color: '#e5e7eb', fontSize: 12, minWidth: 200 },
  expandBtn: { padding: '6px 10px', background: 'transparent', color: '#cbd5e1', border: '1px solid #334155', borderRadius: 4, fontSize: 12, cursor: 'pointer' },
  detailGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginTop: 12, paddingTop: 10, borderTop: '1px solid #1f2937' },
  detailTitle: { fontSize: 11, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: 0.5, fontWeight: 700, marginBottom: 6 },
  barsRow: { display: 'flex', gap: 1, alignItems: 'flex-end', height: 60, padding: '4px 0', position: 'relative' },
  barCol: { flex: 1, height: '100%', display: 'flex', flexDirection: 'column', justifyContent: 'flex-end', position: 'relative' },
  bar: { width: '100%', minHeight: 2, borderRadius: '2px 2px 0 0' },
  barTick: { position: 'absolute', bottom: -14, left: 0, fontSize: 9, color: '#64748b', whiteSpace: 'nowrap' },
  flipList: { paddingLeft: 18, fontSize: 13, color: '#cbd5e1', lineHeight: 1.7, margin: 0 },
};
