import React, { useState, useMemo } from 'react';
import { ModulePage, ModuleSection, MetricGrid, Pill } from '../../components/ModuleShell.js';
import { ProvenancePill } from '../../components/ProvenancePill.js';
import { BMS_EXPORT_META, bmsExportMeters } from '../../data/bmsExportApr2026.js';
import { getBmsMeterMap, setBmsMeterMapping, clearBmsMeterMappings } from '../../data/bmsExportMapping.js';
import { getEffectiveBuildings } from '../../data/assetInventory.js';

// /admin/bms-export — read-only view of the parsed BMS Meter Trends
// CSV plus a meter→building mapping form. Once a meter is mapped, the
// /api/meters/readings endpoint and the public /buildings + /hotspots
// pages start showing measured data for that building.
//
// The export itself is regenerated by re-running
//   node scripts/parseBmsExport.mjs <new.csv> src/data/bmsExportApr2026.js
// and committing the result. This page does not ingest a CSV directly
// — that's a follow-up if the CSV-upload-in-browser flow is wanted.

export default function AdminBmsExport() {
  const [tick, setTick] = useState(0);
  const refresh = () => setTick((t) => t + 1);
  const [filter, setFilter] = useState('');
  const [showOnlyUnmapped, setShowOnlyUnmapped] = useState(false);

  const buildings = useMemo(() => getEffectiveBuildings(), []);
  const map = useMemo(() => getBmsMeterMap(), [tick]);

  const totalCampusKwh = bmsExportMeters
    .filter((m) => m.id.includes('MainFeed') || m.id.endsWith('PanelFeed') || m.id.endsWith('_Main'))
    .reduce((s, m) => s + m.totalKwh, 0);
  const mappedCount = bmsExportMeters.filter((m) => map[m.id]).length;
  const totalRecordedKwh = bmsExportMeters.reduce((s, m) => s + m.totalKwh, 0);

  const filteredRows = bmsExportMeters
    .filter((m) => !filter || m.id.toLowerCase().includes(filter.toLowerCase()))
    .filter((m) => !showOnlyUnmapped || !map[m.id]);

  return (
    <ModulePage
      title="BMS Meter Trends export"
      subtitle="Compact summary parsed from the KUA Distech Eclypse Meter Trends CSV. Map each PM device to a building below — once mapped, every chart on the dashboard that touches that building flips estimated → measured for the export window."
    >
      <ModuleSection title="Source window">
        <MetricGrid metrics={[
          { label: 'Window start',    value: BMS_EXPORT_META.windowStartIso.slice(0, 16).replace('T', ' '), accent: '#22d3ee' },
          { label: 'Window end',      value: BMS_EXPORT_META.windowEndIso.slice(0, 16).replace('T', ' '),   accent: '#22d3ee' },
          { label: 'Hours covered',   value: BMS_EXPORT_META.hoursCovered,                                  accent: '#fbbf24' },
          { label: 'Meters',          value: BMS_EXPORT_META.meterCount,                                    accent: '#86efac' },
          { label: 'Mapped → building', value: `${mappedCount} / ${BMS_EXPORT_META.meterCount}`,            accent: mappedCount === BMS_EXPORT_META.meterCount ? '#22c55e' : '#f59e0b' },
          { label: 'Total kWh',       value: Math.round(totalRecordedKwh).toLocaleString(),                 accent: '#a855f7', note: 'sum of all meters in window' },
        ]} />
        <div style={styles.metaRow}>
          <ProvenancePill provenance="measured" />
          <span style={styles.metaText}>Source: <code>{BMS_EXPORT_META.sourceFile}</code> · parsed {BMS_EXPORT_META.generatedAt.slice(0, 10)}</span>
          <span style={styles.metaText}>To refresh: re-run <code>node scripts/parseBmsExport.mjs &lt;newer.csv&gt; src/data/bmsExportApr2026.js</code> and commit.</span>
        </div>
      </ModuleSection>

      <ModuleSection
        title={`Meters (${filteredRows.length} of ${bmsExportMeters.length})`}
        hint="Sorted by total kWh in the window. Use the dropdown on each row to map PM devices to KUA buildings — once mapped, the dashboard reads measured data for that building's load shape."
      >
        <div style={styles.controls}>
          <input
            type="text"
            value={filter}
            onChange={(e) => setFilter(e.target.value)}
            placeholder="Filter by meter id (e.g. PM_17, Solar, Dryer)"
            style={styles.input}
          />
          <label style={styles.checkboxLabel}>
            <input type="checkbox" checked={showOnlyUnmapped} onChange={(e) => setShowOnlyUnmapped(e.target.checked)} />
            Show only unmapped
          </label>
          <button
            type="button"
            style={styles.dangerBtn}
            onClick={() => {
              if (window.confirm('Clear ALL meter→building mappings? Cannot be undone.')) {
                clearBmsMeterMappings();
                refresh();
              }
            }}
          >
            Clear all mappings
          </button>
        </div>

        <div style={styles.list}>
          {filteredRows.map((m) => (
            <MeterRow
              key={m.id}
              meter={m}
              mappedTo={map[m.id]}
              buildings={buildings}
              onMap={(buildingId) => { setBmsMeterMapping(m.id, buildingId); refresh(); }}
            />
          ))}
        </div>
      </ModuleSection>

      <ModuleSection title="What flips estimated → measured once mapped">
        <ul style={styles.flipList}>
          <li><Pill kind="info">/buildings</Pill> the building's daily kWh column for the export window switches from seasonal-pattern proxy to BMS-measured.</li>
          <li><Pill kind="info">/buildings sparkline</Pill> the campus seasonal pattern adds a measured stretch (Apr 5 – May 4) on top of the existing Jan-Apr master-meter months.</li>
          <li><Pill kind="info">/hotspots</Pill> April + May daily totals come from the export rather than the projection layer.</li>
          <li><Pill kind="info">/trends</Pill> Trend Builder picks up the new meter ids in the building dropdown; selecting one returns hourly samples from the parsed export.</li>
          <li><Pill kind="info">Solar arrays</Pill> mapped solar feeds (PM_15_RoofTopSolarFeed, PM_15_FieldSolarFeed, PM_19_SolarFeed) become the cited source for SOLAR_ANNUAL_KWH on the Executive page.</li>
        </ul>
      </ModuleSection>
    </ModulePage>
  );
}

function MeterRow({ meter, mappedTo, buildings, onMap }) {
  const [expanded, setExpanded] = useState(false);
  const looksLikeSolar = /Solar/i.test(meter.id);
  const looksLikeHeatPump = /HP\d|HeatPump/i.test(meter.id);
  const looksLikeSubmeter = !meter.id.endsWith('MainFeed');

  return (
    <div style={{ ...styles.row, borderLeftColor: mappedTo ? '#22c55e' : '#475569' }}>
      <div style={styles.rowHead}>
        <div style={styles.rowMain}>
          <div style={styles.rowName}>
            <code>{meter.id}</code>
            {looksLikeSolar    && <span style={{ marginLeft: 8 }}><Pill kind="good">Solar</Pill></span>}
            {looksLikeHeatPump && <span style={{ marginLeft: 8 }}><Pill kind="info">Heat pump</Pill></span>}
            {looksLikeSubmeter && <span style={{ marginLeft: 8 }}><Pill kind="neutral">Submeter</Pill></span>}
          </div>
          <div style={styles.rowStats}>
            <span><strong>{meter.totalKwh.toLocaleString()}</strong> kWh</span>
            <span>peak <strong>{meter.peakKw}</strong> kW</span>
            <span>avg <strong>{meter.avgKw}</strong> kW</span>
            <span>{meter.sampleCount} samples</span>
            {meter.droppedOutliers > 0 && <span style={styles.dropped}>{meter.droppedOutliers} outlier{meter.droppedOutliers === 1 ? '' : 's'} filtered</span>}
          </div>
        </div>
        <div style={styles.rowMapping}>
          <select
            value={mappedTo || ''}
            onChange={(e) => onMap(e.target.value || null)}
            style={styles.select}
          >
            <option value="">— unmapped —</option>
            {buildings.map((b) => (
              <option key={b.id} value={b.id}>{b.name}</option>
            ))}
          </select>
          <button type="button" style={styles.expandBtn} onClick={() => setExpanded((v) => !v)}>
            {expanded ? 'Hide' : 'Detail'}
          </button>
        </div>
      </div>
      {expanded && (
        <div style={styles.detailGrid}>
          <div>
            <div style={styles.detailTitle}>Hour-of-day load shape (mean kW)</div>
            <HourlyBars hourly={meter.hourly} />
          </div>
          <div>
            <div style={styles.detailTitle}>Daily totals (kWh)</div>
            <DailyBars daily={meter.daily} />
          </div>
        </div>
      )}
    </div>
  );
}

function HourlyBars({ hourly }) {
  const max = Math.max(...hourly, 1);
  return (
    <div style={styles.barsRow}>
      {hourly.map((kw, i) => (
        <div key={i} style={styles.barCol}>
          <div style={{ ...styles.bar, height: `${Math.round((kw / max) * 100)}%`, background: i >= 6 && i < 18 ? '#fbbf24' : '#475569' }} title={`${i}:00 — ${kw} kW`} />
          {(i % 6 === 0 || i === 23) && <div style={styles.barTick}>{i}</div>}
        </div>
      ))}
    </div>
  );
}

function DailyBars({ daily }) {
  if (!daily.length) return <div style={{ fontSize: 11, color: '#64748b' }}>No daily data.</div>;
  const max = Math.max(...daily.map((d) => d.kwh), 1);
  return (
    <div style={styles.barsRow}>
      {daily.map((d, i) => (
        <div key={d.date} style={styles.barCol}>
          <div style={{ ...styles.bar, height: `${Math.round((d.kwh / max) * 100)}%`, background: '#22c55e' }} title={`${d.date} — ${d.kwh.toLocaleString()} kWh, peak ${d.peakKw} kW`} />
          {(i === 0 || i === daily.length - 1 || i % 7 === 0) && <div style={styles.barTick}>{d.date.slice(5)}</div>}
        </div>
      ))}
    </div>
  );
}

const styles = {
  metaRow: { display: 'flex', gap: 18, alignItems: 'center', marginTop: 14, flexWrap: 'wrap', fontSize: 12, color: '#94a3b8' },
  metaText: { fontSize: 12, color: '#94a3b8' },
  controls: { display: 'flex', gap: 12, marginBottom: 14, alignItems: 'center', flexWrap: 'wrap' },
  input: { padding: '8px 12px', background: '#0b1220', border: '1px solid #334155', borderRadius: 6, color: '#e5e7eb', fontSize: 13, minWidth: 280 },
  checkboxLabel: { display: 'flex', alignItems: 'center', gap: 6, fontSize: 13, color: '#cbd5e1' },
  dangerBtn: { padding: '8px 14px', background: 'transparent', color: '#fca5a5', border: '1px solid #7f1d1d', borderRadius: 6, fontSize: 12, cursor: 'pointer' },
  list: { display: 'grid', gap: 6 },
  row: { padding: '10px 12px', background: '#0b1220', border: '1px solid #1f2937', borderLeft: '4px solid #475569', borderRadius: 6 },
  rowHead: { display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'center', flexWrap: 'wrap' },
  rowMain: { flex: 1 },
  rowName: { fontSize: 13, color: '#e5e7eb', fontWeight: 600 },
  rowStats: { display: 'flex', gap: 14, marginTop: 4, fontSize: 12, color: '#94a3b8', flexWrap: 'wrap', fontVariantNumeric: 'tabular-nums' },
  dropped: { color: '#fbbf24' },
  rowMapping: { display: 'flex', gap: 6, alignItems: 'center' },
  select: { padding: '6px 8px', background: '#0b1220', border: '1px solid #334155', borderRadius: 4, color: '#e5e7eb', fontSize: 12, minWidth: 200 },
  expandBtn: { padding: '6px 10px', background: 'transparent', color: '#cbd5e1', border: '1px solid #334155', borderRadius: 4, fontSize: 12, cursor: 'pointer' },
  detailGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginTop: 12, paddingTop: 10, borderTop: '1px solid #1f2937' },
  detailTitle: { fontSize: 11, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: 0.5, fontWeight: 700, marginBottom: 6 },
  barsRow: { display: 'flex', gap: 1, alignItems: 'flex-end', height: 60, padding: '4px 0', position: 'relative' },
  barCol: { flex: 1, height: '100%', display: 'flex', flexDirection: 'column', justifyContent: 'flex-end', position: 'relative' },
  bar: { width: '100%', minHeight: 2, borderRadius: '2px 2px 0 0' },
  barTick: { position: 'absolute', bottom: -14, left: 0, fontSize: 9, color: '#64748b', whiteSpace: 'nowrap' },
  flipList: { paddingLeft: 18, fontSize: 13, color: '#cbd5e1', lineHeight: 1.7, margin: 0 },
};
